# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-20 11:58
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('_Auth', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='site_info',
            table=None,
        ),
    ]
