# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-21 10:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('_Auth', '0002_pass'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pass',
            name='password',
            field=models.CharField(max_length=150, unique=True),
        ),
        migrations.AlterField(
            model_name='pass',
            name='user',
            field=models.CharField(max_length=150, unique=True),
        ),
    ]
