# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-20 12:07
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Jobs', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Shopping_list_items',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(default='', max_length=100)),
                ('quantity', models.IntegerField(default=1)),
                ('model', models.CharField(default='Shopping_list_items', max_length=100)),
                ('job', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Jobs.Jobs')),
            ],
        ),
    ]
