# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-20 10:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    state_operations = [
        migrations.CreateModel(
            name='Shopping_list_items',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(default='', max_length=100)),
                ('quantity', models.IntegerField(default=1)),
                ('job', models.IntegerField(blank=True, null=True)),
                ('model', models.CharField(default='Shopping_list_items', max_length=100)),
            ],
            options={
                'db_table':'Shopping_list_shopping_list_items',
            },
            bases=(models.Model,),
        ),
    ]

    operations=[
        migrations.SeparateDatabaseAndState(state_operations=state_operations)
    ]