# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-20 11:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('home', '0006_auto_20171220_1144')
    ]

    state_operations = [
        migrations.CreateModel(
            name='Notes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Title', models.CharField(default='', max_length=100)),
                ('Text', models.TextField(default='')),
                ('Timestamp', models.DateTimeField(auto_now_add=True)),
                ('job', models.IntegerField(blank=True, null=True)),
                ('model', models.CharField(default='Notes', max_length=100)),
            ],
            options={
                'db_table':'Notes_notes',
                'ordering': ('-Timestamp',),
            },
            bases=(models.Model,),
        ),
    ]

    operations=[
        migrations.SeparateDatabaseAndState(state_operations=state_operations)
    ]
