# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-20 10:12
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Notes', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notes',
            name='job',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Jobs.Jobs'),
        ),
        migrations.AlterModelTable(
            name='notes',
            table=None,
        ),
    ]
