# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-04 11:32
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Items',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(default='', max_length=100)),
                ('fullname', models.CharField(default='', max_length=100)),
                ('delivery_location', models.CharField(default='', max_length=100)),
                ('price', models.IntegerField(default=1)),
                ('status', models.CharField(default='', max_length=100)),
                ('order_date', models.CharField(default='', max_length=100)),
                ('delivery_date', models.CharField(default='', max_length=100)),
                ('quantity', models.IntegerField(default=1)),
                ('model', models.CharField(default='Items', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Jobs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=100)),
                ('email', models.CharField(default='', max_length=100)),
                ('phone', models.CharField(default='', max_length=100)),
                ('address', models.CharField(default='', max_length=100)),
                ('job_id', models.CharField(default='', max_length=100, unique=True)),
                ('status', models.CharField(default='quote', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Notes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Title', models.CharField(default='', max_length=100)),
                ('Text', models.CharField(default='', max_length=100)),
                ('Timestamp', models.DateTimeField(auto_now_add=True)),
                ('model', models.CharField(default='Notes', max_length=100)),
                ('job', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='home.Jobs')),
            ],
            options={
                'ordering': ('-Timestamp',),
            },
        ),
        migrations.CreateModel(
            name='Purchase_orders',
            fields=[
                ('supplier', models.CharField(default='', max_length=100)),
                ('supplier_ref', models.CharField(default='', max_length=100)),
                ('order_no', models.AutoField(primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Scheduled_items',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(default='', max_length=100)),
                ('date_1', models.DateField(default=django.utils.timezone.now)),
                ('date_2', models.DateField(default=models.DateField(default=django.utils.timezone.now))),
                ('quantity', models.IntegerField(default=1)),
                ('model', models.CharField(default='Scheduled_items', max_length=100)),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.Jobs')),
            ],
        ),
        migrations.CreateModel(
            name='Shopping_list_items',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(default='', max_length=100)),
                ('quantity', models.IntegerField(default=1)),
                ('model', models.CharField(default='Shopping_list_items', max_length=100)),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.Jobs')),
            ],
        ),
        migrations.CreateModel(
            name='Site_info',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('locked', models.BooleanField(default=False)),
                ('password', models.CharField(max_length=150)),
            ],
        ),
        migrations.AddField(
            model_name='items',
            name='PO',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='home.Purchase_orders'),
        ),
        migrations.AddField(
            model_name='items',
            name='job',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.Jobs'),
        ),
    ]
