# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-11 17:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_auto_20171208_1649'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notes',
            name='Text',
            field=models.TextField(default=''),
        ),
    ]
