# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-14 10:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_auto_20171211_1726'),
    ]

    operations = [
        migrations.AlterField(
            model_name='items',
            name='price',
            field=models.DecimalField(decimal_places=2, default=1.0, max_digits=25),
        ),
    ]
