# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-22 07:24
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_auto_20171122_0604'),
    ]

    operations = [
        migrations.RenameField(
            model_name='scheduled_items',
            old_name='date1',
            new_name='date_1',
        ),
        migrations.RenameField(
            model_name='scheduled_items',
            old_name='date2',
            new_name='date_2',
        ),
    ]
