# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-22 08:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_auto_20171122_0724'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scheduled_items',
            name='date_2',
            field=models.DateField(default=''),
        ),
    ]
