# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-22 08:21
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_auto_20171122_0820'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scheduled_items',
            name='date_2',
            field=models.DateField(default=models.DateField(default=django.utils.timezone.now)),
        ),
    ]
