# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-22 15:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_auto_20171122_0821'),
    ]

    operations = [
        migrations.AddField(
            model_name='notes',
            name='model',
            field=models.CharField(default='Notes', max_length=100),
        ),
        migrations.AddField(
            model_name='scheduled_items',
            name='model',
            field=models.CharField(default='Scheduled_items', max_length=100),
        ),
    ]
