# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-25 16:06
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_auto_20171122_1546'),
    ]

    operations = [
        migrations.CreateModel(
            name='Items',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(default='', max_length=100)),
                ('fullname', models.CharField(default='', max_length=100)),
                ('delivery_location', models.CharField(default='', max_length=100)),
                ('price', models.IntegerField(default=1)),
                ('status', models.CharField(default='', max_length=100)),
                ('order_date', models.CharField(default='', max_length=100)),
                ('delivery_date', models.CharField(default='', max_length=100)),
                ('quantity', models.IntegerField(default=1)),
            ],
        ),
        migrations.CreateModel(
            name='Purchase_orders',
            fields=[
                ('supplier', models.CharField(default='', max_length=100)),
                ('supplier_ref', models.CharField(default='', max_length=100)),
                ('order_no', models.IntegerField(primary_key=True, serialize=False)),
            ],
        ),
        migrations.AlterField(
            model_name='scheduled_items',
            name='description',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='items',
            name='PO',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.Purchase_orders'),
        ),
        migrations.AddField(
            model_name='items',
            name='job',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.Jobs'),
        ),
    ]
