# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-29 10:59
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_auto_20171125_1606'),
    ]

    operations = [
        migrations.CreateModel(
            name='Shopping_list_items',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(default='', max_length=100)),
                ('quantity', models.IntegerField(default=1)),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.Jobs')),
            ],
        ),
    ]
