# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-29 12:19
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0009_shopping_list_items'),
    ]

    operations = [
        migrations.AlterField(
            model_name='items',
            name='PO',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='home.Purchase_orders'),
        ),
    ]
