# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-29 13:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0010_auto_20171129_1219'),
    ]

    operations = [
        migrations.AddField(
            model_name='items',
            name='model',
            field=models.CharField(default='Items', max_length=100),
        ),
        migrations.AddField(
            model_name='shopping_list_items',
            name='model',
            field=models.CharField(default='Shopping_list_items', max_length=100),
        ),
    ]
