# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-20 09:56
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    state_operations = [
        migrations.CreateModel(
            name='Items',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(default='', max_length=100)),
                ('fullname', models.CharField(default='', max_length=100)),
                ('delivery_location', models.CharField(default='', max_length=100)),
                ('price', models.DecimalField(decimal_places=2, default=1.0, max_digits=25)),
                ('status', models.CharField(default='', max_length=100)),
                ('order_date', models.CharField(default='', max_length=100)),
                ('delivery_date', models.CharField(default='', max_length=100)),
                ('quantity', models.IntegerField(default=1)),
                ('PO', models.IntegerField(blank=True, null=True)),
                ('job', models.IntegerField(blank=True, null=True)),
                ('model', models.CharField(default='Items', max_length=100)),
            ],
            options={
                'db_table':'Item_Flow_items',
            },
            bases=(models.Model,),
        ),
        migrations.CreateModel(
            name='Purchase_orders',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('supplier', models.CharField(default='', max_length=100)),
                ('supplier_ref', models.CharField(default='', max_length=100)),
            ],
            options={
                'db_table':'Item_Flow_purchase_orders',
            },
            bases=(models.Model,),
        ),
        migrations.CreateModel(
            name='Scheduled_items',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(default='', max_length=100)),
                ('date_1', models.DateField(default=django.utils.timezone.now)),
                ('date_2', models.DateField(default=models.DateField(default=django.utils.timezone.now))),
                ('quantity', models.IntegerField(default=1)),
                ('job', models.IntegerField(blank=True, null=True)),
                ('model', models.CharField(default='Scheduled_items', max_length=100)),
            ],
            options={
                'db_table':'Item_Flow_scheduled_items',
            },
            bases=(models.Model,),
        ),
    ]

    operations=[
        migrations.SeparateDatabaseAndState(state_operations=state_operations)
    ]
