# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-20 11:58
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Item_Flow', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='items',
            name='PO',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Item_Flow.Purchase_orders'),
        ),
        migrations.AlterField(
            model_name='items',
            name='job',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Jobs.Jobs'),
        ),
        migrations.AlterField(
            model_name='scheduled_items',
            name='job',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Jobs.Jobs'),
        ),
        migrations.AlterModelTable(
            name='items',
            table=None,
        ),
        migrations.AlterModelTable(
            name='purchase_orders',
            table=None,
        ),
        migrations.AlterModelTable(
            name='scheduled_items',
            table=None,
        ),
    ]
